apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-deployment
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: apache/tika:2.8.0.0
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
  name: tika-service
spec:
  type: NodePort
  selector:
    app: tika
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
      nodePort: 30200
